import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readdirSync, readFileSync } from 'node:fs';
import { createLoginToken, verifyLoginToken, setOrderCookie, canAccessOrder, getSessionEmail, setSessionCookie } from '../src/lib/session.ts';
import { signingSecret } from '../src/lib/tokens.ts';
import { ensurePurchase, getPurchase, reissueToken, markRefunded, activePurchase, claimResend } from '../src/lib/purchases.ts';
import { queueDelivery, deliverPurchases } from '../src/lib/delivery.ts';
import { saveReview, getSummary, listReviews } from '../src/lib/reviews.ts';
import { rateLimit } from '../src/lib/rate-limit.ts';
import { subscribe, createNewsletter, removeSubscriber, deliverPending, retryFailedLetters } from '../src/lib/newsletter.ts';

function environment() {
 const db=new DatabaseSync(':memory:');
 for(const name of readdirSync(new URL('../migrations/',import.meta.url)).sort()) db.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));
 const prepare=sql=>{let values=[];const run=()=>{const stmt=db.prepare(sql);stmt.setAllowBareNamedParameters(true);const params=Object.fromEntries(values.map((v,i)=>[String(i+1),v]));return {stmt,params};};return {bind(...v){values=v;return this;},async run(){const {stmt,params}=run();const r=stmt.run(params);return {meta:{changes:Number(r.changes)}};},async first(){const {stmt,params}=run();return stmt.get(params)??null;},async all(){const {stmt,params}=run();return {results:stmt.all(params)};}};};
 const env={DB:{prepare,batch:async queries=>{db.exec('BEGIN');try{const r=await Promise.all(queries.map(q=>q.run()));db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}},AUTH_SECRET:'a'.repeat(48),SITE_URL:'https://shop.example',EMAIL_FROM:'shop@example.com'};
 return {env,db};
}
function context(){const cookies=new Map();return {url:new URL('https://shop.example/thank-you'),cookies:{set:(k,v)=>cookies.set(k,{value:v}),get:k=>cookies.get(k),delete:k=>cookies.delete(k)}};}
function paid(id='cs_live_1',email='reader@example.com'){return {id,mode:'payment',payment_status:'paid',customer_details:{email},metadata:{guide:'ai-assistants',consent_at:'2026-09-10T00:00:00Z',terms_version:'2026-09-10'},payment_intent:'pi_'+id,livemode:true,amount_total:3900,currency:'usd',created:1788998400};}

test('all migrations apply; auth fails closed without a strong secret',()=>{environment();assert.throws(()=>signingSecret({}),/AUTH_SECRET/);assert.throws(()=>signingSecret({AUTH_SECRET:'short'}));});
test('magic links are hashed, expire, and atomically consumed once',async()=>{const {env,db}=environment();const token=await createLoginToken(env,'READER@example.com');assert.equal(db.prepare('SELECT digest FROM login_tokens').get().digest===token,false);const results=await Promise.all([verifyLoginToken(env,token),verifyLoginToken(env,token)]);assert.deepEqual(results.sort(),['reader@example.com',null].sort());const expired=await createLoginToken(env,'x@example.com');db.exec('UPDATE login_tokens SET expires_at=0');assert.equal(await verifyLoginToken(env,expired),null);});
test('checkout cookie grants one order, never an account',async()=>{const {env}=environment();const ctx=context();assert.equal(await canAccessOrder(ctx,env,'cs_a','x@example.com'),false);await setOrderCookie(ctx,env,'cs_a');assert.equal(await canAccessOrder(ctx,env,'cs_a','x@example.com'),true);assert.equal(await canAccessOrder(ctx,env,'cs_b','x@example.com'),false);assert.equal(await getSessionEmail(ctx,env),null);const value=ctx.cookies.get('ug_order').value;ctx.cookies.set('ug_order',value.replace('cs_a','cs_b'));assert.equal(await canAccessOrder(ctx,env,'cs_b','x@example.com'),false);});
test('signed account can only access its own orders',async()=>{const {env}=environment();const ctx=context();await setSessionCookie(ctx,env,'reader@example.com');assert.equal(await canAccessOrder(ctx,env,'cs_a','reader@example.com'),true);assert.equal(await canAccessOrder(ctx,env,'cs_a','other@example.com'),false);});
test('unpaid sessions create no purchase; duplicates preserve the same token and consent',async()=>{const {env,db}=environment();assert.equal(await ensurePurchase(env,{...paid(),payment_status:'unpaid'}),null);const p=await ensurePurchase(env,paid());const again=await ensurePurchase(env,paid());assert.equal(p.token,again.token);assert.equal(p.consent_at,'2026-09-10T00:00:00Z');assert.equal(db.prepare('SELECT COUNT(*) n FROM purchases').get().n,1);});
test('concurrent expiry renewal returns one token',async()=>{const {env,db}=environment();await ensurePurchase(env,paid());db.exec("UPDATE purchases SET token_issued_at='2000-01-01T00:00:00Z'");const old=await getPurchase(env,'cs_live_1');const results=await Promise.all([reissueToken(env,old),reissueToken(env,old)]);assert.equal(results[0].token,results[1].token);assert.notEqual(results[0].token,old.token);assert.equal(results[0].reissues,1);});
test('refund revokes tokens, prevents renewal and replayed purchase events',async()=>{const {env}=environment();const p=await ensurePurchase(env,paid());await queueDelivery(env,p.session_id);await markRefunded(env,p.session_id);const refunded=await getPurchase(env,p.session_id);assert.equal(refunded.token,null);assert.equal(activePurchase(refunded),false);await assert.rejects(()=>reissueToken(env,refunded));assert.equal(await ensurePurchase(env,paid()),null);});
test('refund received before checkout completion prevents fulfilment',async()=>{const {env,db}=environment();db.prepare('INSERT INTO refunded_payments VALUES (?,?)').run('pi_cs_live_1','now');assert.equal(await ensurePurchase(env,paid()),null);});
test('delivery failure is queued durably, then retry succeeds once under concurrent workers',async()=>{const {env,db}=environment();let sends=0;env.SEND_EMAIL={send:async()=>{sends++;if(sends===1)throw new Error('simulated provider outage');return {messageId:'test'};}};const p=await ensurePurchase(env,paid());await queueDelivery(env,p.session_id);await deliverPurchases(env,env.SITE_URL);assert.equal(db.prepare('SELECT completed_at FROM delivery_jobs').get().completed_at,null);assert.ok(db.prepare('SELECT next_attempt_at FROM delivery_jobs').get().next_attempt_at>Date.now());db.exec('UPDATE delivery_jobs SET next_attempt_at=0');await Promise.all([deliverPurchases(env,env.SITE_URL),deliverPurchases(env,env.SITE_URL)]);assert.equal(sends,2);assert.ok(db.prepare('SELECT completed_at FROM delivery_jobs').get().completed_at);});
test('resend cooldown is atomic',async()=>{const {env}=environment();const p=await ensurePurchase(env,paid());assert.deepEqual((await Promise.all([claimResend(env,p),claimResend(env,p)])).sort(),[false,true]);});
test('review summaries include authentic positive and negative buyers, exclude test and unverified rows',async()=>{const {env,db}=environment();await ensurePurchase(env,paid());await saveReview(env,{email:'reader@example.com',guide:'ai-assistants',rating:1,body:'Needs more examples',displayName:'Reader'});await ensurePurchase(env,paid('cs_live_2','second@example.com'));await saveReview(env,{email:'second@example.com',guide:'ai-assistants',rating:5,body:'Useful',displayName:'Second'});db.exec("INSERT INTO reviews(guide,email,rating,created_at,updated_at) VALUES('ai-assistants','seed@example.test',5,'now','now')");assert.equal((await getSummary(env,'ai-assistants')).average,3);assert.equal((await listReviews(env,'ai-assistants')).length,2);await markRefunded(env,'cs_live_2');assert.equal((await getSummary(env,'ai-assistants')).average,1);});
test('fixed-window rate limiter accepts quota and rejects excess',async()=>{const {env}=environment();const results=await Promise.all(Array.from({length:4},()=>rateLimit(env,'test','person',3,600000)));assert.equal(results.filter(Boolean).length,3);});
test('newsletter unsubscribe cancels already queued recipients',async()=>{const {env,db}=environment();let sent=0;env.SEND_EMAIL={send:async()=>{sent++;return {messageId:'test'};}};await subscribe(env,env.SITE_URL,'reader@example.com','*','test');db.exec("UPDATE signups SET confirmed_at='now'");await createNewsletter(env,'A letter','Body');await removeSubscriber(env,'reader@example.com');await deliverPending(env,env.SITE_URL);assert.equal(sent,1);assert.equal(db.prepare('SELECT error FROM newsletter_recipients').get().error,'unsubscribed');});
test('newsletter leases prevent duplicate sends and retries respect unsubscribes',async()=>{const {env,db}=environment();let sent=0;env.SEND_EMAIL={send:async()=>{sent++;return {messageId:'test'};}};await subscribe(env,env.SITE_URL,'reader@example.com','*','test');db.exec("UPDATE signups SET confirmed_at='now'");await createNewsletter(env,'A letter','Body');await Promise.all([deliverPending(env,env.SITE_URL),deliverPending(env,env.SITE_URL)]);assert.equal(sent,2);assert.equal(db.prepare('SELECT sent FROM newsletters').get().sent,1);await removeSubscriber(env,'reader@example.com');await retryFailedLetters(env);assert.equal(db.prepare('SELECT sent FROM newsletters').get().sent,1);});
